"""fixed class size stuff

Revision ID: 167b6d40451c
Revises: e57e1f9c4be3
Create Date: 2026-04-14 06:33:36.789878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167b6d40451c'
down_revision = 'e57e1f9c4be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollmentActual', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('enrollmentMax', sa.Integer(), server_default=sa.text('(50)'), nullable=False))
        batch_op.drop_column('enrollment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_column('enrollmentMax')
        batch_op.drop_column('enrollmentActual')

    # ### end Alembic commands ###
