"""fixed enrollment names

Revision ID: 70e9401c2b51
Revises: 167b6d40451c
Create Date: 2026-04-14 06:39:30.819426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e9401c2b51'
down_revision = '167b6d40451c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), server_default=sa.text('(50)'), nullable=False))
        batch_op.drop_column('enrollmentActual')
        batch_op.drop_column('enrollmentMax')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollmentMax', sa.INTEGER(), server_default=sa.text('(50)'), nullable=False))
        batch_op.add_column(sa.Column('enrollmentActual', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
        batch_op.drop_column('capacity')
        batch_op.drop_column('enrollment')

    # ### end Alembic commands ###
