"""add more tables and info

Revision ID: ddba3eb35fce
Revises: b544da509d1f
Create Date: 2026-04-14 05:45:57.650616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddba3eb35fce'
down_revision = 'b544da509d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classname', sa.String(length=80), nullable=False),
    sa.Column('timing', sa.String(length=120), nullable=False),
    sa.Column('teacher', sa.String(length=120), nullable=False),
    sa.Column('enrollment', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timing')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('enrollment')
    op.drop_table('classes')
    # ### end Alembic commands ###
