"""removed post

Revision ID: e57e1f9c4be3
Revises: ddba3eb35fce
Create Date: 2026-04-14 06:20:20.680737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57e1f9c4be3'
down_revision = 'ddba3eb35fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('classes')
    op.drop_table('teachers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('classname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('timing', sa.VARCHAR(length=120), nullable=False),
    sa.Column('teacher', sa.VARCHAR(length=120), nullable=False),
    sa.Column('enrollment', sa.VARCHAR(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timing')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
