"""added username to student and teacher

Revision ID: f8769572b1dc
Revises: 2b755439b549
Create Date: 2026-04-14 07:15:26.460825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8769572b1dc'
down_revision = '2b755439b549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), server_default='defaultStudent', nullable=False))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), server_default='defaultTeach', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
